openapi: 3.0.0
info:
  title: 'Invoice search API'
  version: 1.0.0
paths:
  /search:
    post:
      summary: Search invoices
      description: |
        This endpoint allows querying the complete invoice information
        using the debtor’s document, the reference, or the alternate reference.  
        **At least 2 of the following 3 parameters must be sent:**
        - `document`
        - `reference`
        - `altReference`
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - auth
              properties:
                auth:
                  $ref: "#/components/schemas/Authentication"
                document:
                  type: string
                  description: Debtor’s invoicing document number
                  example: "1234567813"
                reference:
                  type: string
                  description: Invoice reference number
                  example: "2024ABC"
                altReference:
                  type: string
                  description: Alternate invoicing reference number
                  example: "02019003"
              example:
                auth:
                  login: "d15aac486fd785cda0e471a83c2b1fdf"
                  tranKey: "dsRL5wIymrySr9TgsYtxWZEIb5/RtW1v3n3xLqQZKj4="
                  nonce: "MTIzNDU2Nzg="
                  seed: "2024-07-31T17:02:49-05:00"
                document: "1234567813"
                altReference: "02019003"
                reference: "2024ABC"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: "#/components/schemas/Status"
                  data:
                    $ref: "#/components/schemas/Invoice"
  /create:
    post:
      summary: Create invoices
      description: |
        This endpoint allows bulk upload of invoices.
        - If an invoice is created with the same reference as an existing one, it will be replaced if not paid.
        - Multiple invoices can be sent in a single request.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - auth
                - invoices
              properties:
                auth:
                  $ref: "#/components/schemas/Authentication"
                invoices:
                  type: array
                  description: List of invoices to create.
                  items:
                    $ref: "#/components/schemas/InvoiceCash"
              example:
                auth:
                  login: "d15aac486fd785cda0e471a83c2b1fdf"
                  tranKey: "fr7/Seny29osBmrWFmHcRU3yRalwEuM/B5KrruXEkac="
                  nonce: "NWYyMTZmMjAzNWU5MA=="
                  seed: "2020-07-29T12:44:16+00:00"
                invoices:
                  - payment:
                      reference: "1234567890129"
                      amount:
                        total: 1.11
                    debtor:
                      document: "1234567899"
                      documentType: "CC"
                    expiration: "2021-03-25T10:14:24-05:00"
                    serviceCode: 1234567890123
                  - payment:
                      reference: "1234567890126"
                      description: "E999"
                      amount:
                        currency: "USD"
                        total: 2.22
                    altReference: "02019035"
                    debtor:
                      document: "123456"
                      documentType: "CE"
                      name: "DAVID JIMENEZ ARBOLEDA"
                    expiration: "2021-03-25T10:14:24-05:00"
                    dueType: 1
                    dueDate: "2021-03-25T10:14:24-05:00"
                    serviceCode: 999
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: "#/components/schemas/Status"
                  count:
                    type: integer
                    description: Number of invoices created.
                    example: 2
                example:
                  status:
                    status: "OK"
                    reason: "00"
                    message: "Invoices created successfully"
                    date: "2025-03-17T22:45:27+00:00"
                  count: 2

  /hold:
    post:
      summary: Hold or release invoicing
      description: |
        This endpoint allows you to **hold** or **release** an invoice.  
        - When an invoice is **held**, its payment status appears as `"in process"` in the admin panel and it cannot be edited or deleted.  
        - To release it, use the field `revoke: true`.  
        - The operation requires the invoice’s **unique ID**, generated by the system.
      tags:
        - Invoices
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                auth:
                  $ref: '#/components/schemas/Authentication'
                invoice:
                  type: integer
                  description: Unique invoicing ID number (system generated).
                  example: 675983
                revoke:
                  type: boolean
                  description: |
                    - `false`: the invoice will be held.  
                    - `true`: the invoice will be released.
                  example: false
              required:
                - auth
                - invoice
                - revoke
      responses:
        '200':
          description: Successful response with invoicing information.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/Status'
                  data:
                    $ref: '#/components/schemas/Invoice'
              example:
                status:
                  status: "OK"
                  reason: "00"
                  message: "The request has been successfully processed"
                  date: "2020-07-29T08:09:35-05:00"
                data:
                  id: 675983
                  status: "ACTIVE"
                  debtor:
                    document: "1234567813"
                    documentType: "CI"
                    name: "ANDREA"
                    surname: "VIDAL FERNANDEZ"
                  payment:
                    reference: "1234889"
                    description: "E955"
                    amount:
                      taxes:
                        - kind: "valueAddedTax"
                          amount: 0
                          base: 0
                        - kind: "airportTax"
                          amount: 0
                          base: 0
                      details:
                        - kind: "subtotal"
                          amount: 30.12
                      currency: "USD"
                      total: 30.12
                    allowPartial: false
                    subscribe: false
                  altReference: "054"
                  createdAt: "2020-07-28"
                  expirationDate: "2021-03-25 10:14:24"
                  finalDate: "2021-04-30 23:59:59"
                  siteId: 40
        '400':
          description: Bad request (invalid parameters or missing data).
        '401':
          description: Authentication error.
        '500':
          description: Internal server error.

  /remove:
    post:
      summary: Remove invoicing
      description: |
        This endpoint allows you to **permanently delete** an invoice.  
        Deletion **cannot be undone**.  
        The response returns the full invoice information as it was registered before deletion.
      tags:
        - Invoices
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                auth:
                  $ref: '#/components/schemas/Authentication'
                invoice:
                  type: integer
                  description: Unique invoicing ID number (system generated).
                  example: 675967
              required:
                - auth
                - invoice
      responses:
        '200':
          description: Successful response with deleted invoicing information.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/Status'
                  data:
                    $ref: '#/components/schemas/Invoice'
              example:
                status:
                  status: "OK"
                  reason: "00"
                  message: "The request has been successfully processed"
                  date: "2020-07-29T08:26:29-05:00"
                data:
                  id: 675967
                  status: "ACTIVE"
                  debtor:
                    document: "1234567899"
                    documentType: "CI"
                    name: "ANDREA"
                    surname: "VIDAL FERNANDEZ"
                  payment:
                    reference: "1234567890129"
                    description: "E993"
                    amount:
                      taxes:
                        - kind: "valueAddedTax"
                          amount: 0
                          base: 0
                        - kind: "airportTax"
                          amount: 0
                          base: 0
                      details:
                        - kind: "subtotal"
                          amount: 1.11
                      currency: "USD"
                      total: 1.11
                    allowPartial: false
                    subscribe: false
                  altReference: "02019039"
                  createdAt: "2020-07-26"
                  expirationDate: "2020-03-25 10:14:24"
                  finalDate: "2021-03-25 23:59:59"
                  siteId: 40
        '400':
          description: Bad request (invalid parameters or missing data).
        '401':
          description: Authentication error.
        '500':
          description: Internal server error.

  /flush:
    post:
      summary: Delete expired invoices
      description: |
        This endpoint allows you to **bulk delete** all invoices whose `expirationDate` is earlier than the current date and time.  
        Only invoices that are **not paid or held** are deleted.  
        The operation is irreversible.
      tags:
        - Invoices
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                auth:
                  $ref: '#/components/schemas/Authentication'
              required:
                - auth
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/Status'
              example:
                status:
                  status: "OK"
                  reason: "00"
                  message: "The request has been successfully processed"
                  date: "2020-07-26T20:01:15-05:00"



components:
  schemas:
    Status:
      title: "Status"
      type: "object"
      description: "Structure that contains information about a request, reporting its current state."
      properties:
        status:
          type: "string"
          description: "Operation status."
          enum:
            - OK
            - FAILED
            - APPROVED
            - REJECTED
            - PENDING
            - MANUAL
            - REFUNDED
          example: "OK"
        reason:
          type: "string"
          description: "Reason for the operation status."
          maxLength: "2"
          example: "00"
        message:
          type: "string"
          description: "Status description."
          example: "The request has been successfully processed"
        date:
          type: "string"
          description: "Date when the operation was executed."
          format: "date-time"
          example: '2025-03-17T22:45:27+00:00'
      required:
        - "status"
        - "reason"
        - "message"
        - "date"
    Authentication:
      title: "Authentication"
      type: "object"
      description: "Authentication object. See more at **[Authentication](/token-requestor/integration/authentication)**. 
        Structure that contains the site's authentication information generated according to the WSSE UsernameToken Profile 1.1."
      properties:
        login:
          type: "string"
          description: "Login for authentication."
          minLength: "1"
          example: "1441d14df19ec88431e513bb990326e1"
        tranKey:
          type: "string"
          description: "Transaction key."
          minLength: "1"
          example: "DGYymv6ohpYwtLWon/iADE/COoo9JXt4jqyk6D006PY="
        nonce:
          type: "string"
          description: "Random value for each request encoded in Base64."
          minLength: "1"
          example: "enQ4dXh3YWhkMWM="
        seed:
          type: "string"
          description: "Current date generated in ISO 8601 format."
          minLength: "1"
          example: "2023-06-21T09:56:06-05:00"
      required:
        - "login"
        - "tranKey"
        - "nonce"
        - "seed"
    Invoice:
      title: "Invoice"
      type: "object"
      description: "Structure containing information about an invoicing."
      properties:
        id:
          type: integer
          description: "Unique invoicing identifier generated by the system."
          example: 675978
        status:
          type: string
          description: "Invoice status."
          enum:
            - PAYED
            - EXPIRED
            - ACTIVE
            - INACTIVE
            - HOLD
          example: "EXPIRED"
        debtor:
          $ref: "#/components/schemas/Debtor"
        payment:
          $ref: "#/components/schemas/Payment"
        altReference:
          type: string
          description: "Alternative invoicing code (max 30 characters)."
          maxLength: 30
          example: "02019039"
        createdAt:
          type: string
          format: date-time
          description: "Date and time when the invoicing was created."
          example: "2020-07-28T08:00:47-05:00"
        expirationDate:
          type: string
          format: date-time
          description: "Invoice expiration date and time in the system."
          example: "2021-03-25T10:14:24-05:00"
        finalDate:
          type: string
          format: date-time
          description: "Deadline for payment (23:59:59 on the expiration day)."
          example: "2020-07-28T23:59:59-05:00"
        dueType:
          type: integer
          description: "Type of overdue increment: [1 = fixed value, 0 = daily value]."
          example: 1
        dueRate:
          type: number
          format: float
          description: "Value to be added to the overdue invoicing."
          example: 5.5
        dueDate:
          type: string
          format: date-time
          description: "Invoice due date and time."
          example: "2021-03-25T10:14:24-05:00"
        expiration:
          type: string
          format: date-time
          description: "Invoice expiration date and time."
          example: "2021-03-25T10:14:24-05:00"
        serviceCode:
          type: integer
          description: "Service or product code billed (max 13 digits)."
          example: 999
        siteId:
          type: integer
          description: "Site identifier."
          example: 40
      required:
        - id
        - status
        - debtor
        - payment
        - createdAt
        - expirationDate
        - finalDate
        - serviceCode
        - siteId

    Debtor:
      title: "Debtor"
      type: "object"
      description: "Structure containing debtor information for the invoicing."
      properties:
        document:
          type: string
          description: "Debtor's document number (max 16 characters)."
          maxLength: 16
          example: "1234567899"
        documentType:
          type: string
          description: "Debtor's document type."
          enum:
            - "CC"
            - "CE"
            - "TI"
            - "NIT"
            - "RUT"
            - "PPN"
            - "TAX"
            - "LIC"
            - "SSN"
            - "CIP"
            - "CPF"
            - "CI"
            - "RUC"
            - "DNI"
            - "CLRUT"
          example: "CC"
        name:
          type: string
          description: "Debtor's name."
          example: "ANDREA"
        surname:
          type: string
          description: "Debtor's surname."
          example: "VIDAL FERNANDEZ"
        email:
          type: string
          description: "Debtor's email address."
          example: "corredebtor@yopmail.com"
      required:
        - document
        - documentType
        - name

    Payment:
      title: "Payment"
      type: "object"
      description: "Structure containing invoicing payment information."
      properties:
        reference:
          type: string
          description: "Reference number (max 32 characters)."
          maxLength: 32
          example: "1234567890129"
        description:
          type: string
          description: "Payment description (max 255 characters)."
          maxLength: 255
          example: "E993"
        amount:
          $ref: "#/components/schemas/Amount"
        allowPartial:
          type: boolean
          description: "Indicates whether partial payments are allowed."
          example: false
        subscribe:
          type: boolean
          description: "Indicates whether subscription is allowed."
          example: false
      required:
        - reference
        - amount

    Amount:
      title: "Amount"
      type: "object"
      description: "Structure containing invoicing amount information."
      properties:
        taxes:
          type: array
          description: "Breakdown of applied taxes."
          items:
            $ref: "#/components/schemas/Tax"
        details:
          type: array
          description: "Additional invoicing details."
          items:
            $ref: "#/components/schemas/AmountDetail"
        currency:
          type: string
          description: "Transaction currency (ISO 4217)."
          example: "USD"
        total:
          type: number
          format: float
          description: "Total invoicing value (maximum 9,999,999,999.99)."
          example: 30.12
      required:
        - currency
        - total

    Tax:
      title: "Tax"
      type: "object"
      description: "Structure containing information about an applied tax."
      properties:
        kind:
          type: string
          description: "Tax classification type."
          example: "valueAddedTax"
        amount:
          type: number
          format: float
          description: "Tax amount."
          example: 0
        base:
          type: number
          format: float
          description: "Base value used to calculate the tax."
          example: 0
      required:
        - kind
        - amount
        - base

    AmountDetail:
      title: "AmountDetail"
      type: "object"
      description: "Structure to store additional amount information."
      properties:
        kind:
          type: string
          description: "Type of additional amount."
          enum:
            - discount
            - additional
            - vatDevolutionBase
            - shipping
            - handlingFee
            - insurance
            - giftWrap
            - subtotal
            - fee
            - tip
          example: "subtotal"
        amount:
          type: number
          format: float
          description: "Monetary value corresponding to the additional type."
          example: 30.12
      required:
        - kind
        - amount
    InvoiceCash:
      title: "InvoiceCash"
      type: object
      description: Invoice to be created in the system.
      properties:
        payment:
          $ref: "#/components/schemas/PaymentCreate"
        debtor:
          $ref: "#/components/schemas/DebtorCreate"
        altReference:
          type: string
          maxLength: 30
          description: Alternative invoicing code.
        expiration:
          type: string
          format: date-time
          description: Invoice expiration date and time.
        dueType:
          type: integer
          description: Overdue increment type [1 = fixed, 0 = daily].
        dueDate:
          type: string
          format: date-time
        serviceCode:
          type: integer
          description: Service code.
      required:
        - payment
        - debtor
        - expiration
        - serviceCode

    PaymentCreate:
      type: object
      properties:
        reference:
          type: string
          description: Unique invoicing reference number.
          example: "1234567890129"
        description:
          type: string
          description: Invoice description.
          example: "E999"
        amount:
          type: object
          properties:
            currency:
              type: string
              example: "USD"
            total:
              type: number
              format: double
              example: 2.22
          required:
            - total
      required:
        - reference
        - amount

    DebtorCreate:
      type: object
      properties:
        document:
          type: string
          example: "1234567899"
        documentType:
          type: string
          example: "CC"
          enum:
            - "CC"
            - "CE"
            - "TI"
            - "NIT"
            - "RUT"
            - "PPN"
            - "TAX"
            - "LIC"
            - "SSN"
            - "CIP"
            - "CPF"
            - "CI"
            - "RUC"
            - "DNI"
            - "CLRUT"
        name:
          type: string
          example: "DAVID JIMENEZ"
      required:
        - document
        - documentType
